/**
 * Platform Shim — injected at build time as the worker's main module.
 *
 * Wraps env bindings before passing to the user's worker:
 * - VIBE_STORAGE: environment-scoped KV key prefixing
 * - VIBE_R2:      environment-scoped R2 key prefixing + path-traversal guards
 *
 * D1 is already per-vibe (separate database per worker), so no wrapping needed.
 *
 * This shim is NOT generated by the agent — it's a platform file checked into
 * the repo and copied into the bundle at build time. Worker code cannot modify
 * or bypass it.
 *
 * NOTE: Only the `fetch` handler is wrapped. If vibe workers ever need
 * `scheduled`, `queue`, or other handlers, forward them here too.
 *
 * TESTABILITY: The security-critical isolation/cap primitives below are also
 * `export`ed as named exports so the unit tests in
 * `scripts/build/__tests__/platform-shim.test.js` exercise the REAL code
 * (not a drifting copy). Named exports are inert at runtime — Workers only
 * invokes the default export's `fetch`. The lazy `./worker.js` import in fetch
 * resolves at deploy time to the bundled vibe worker uploaded as a sibling
 * module (see cf-api.ts), and at test time to the test-only stub
 * `scripts/build/worker.js`.
 */
import { AsyncLocalStorage } from 'node:async_hooks';

// Access-mode enforcement capability version of THIS shim.
// The build-runner reads this literal out of the shim source it stages and
// reports it to the platform, which records it as vibe_runtime.shimVersion — so
// the recorded version reflects the shim a vibe was ACTUALLY built with (not a
// platform constant that could drift during a deploy). Keep in lockstep with
// SHIM_VERSION in src/config/shim-version.ts (a test asserts they match).
// What this version enforces: read mode treats idempotent schema DDL
// (CREATE … IF NOT EXISTS), alone or inside batch(), as a no-op rather than a
// denial; preview KV/R2 data is isolated from production, and a missing or
// unknown VIBE_ENV is treated as production. The meaning of each version
// number is documented beside SHIM_VERSION.
const PLATFORM_SHIM_VERSION = 6;
void PLATFORM_SHIM_VERSION;

// Capture these before any user module code executes. Invoking the captured
// methods with .call prevents later prototype monkey-patching from bypassing
// the request-local access mode.
const _alsRun = AsyncLocalStorage.prototype.run;
const _alsGetStore = AsyncLocalStorage.prototype.getStore;
const als = new AsyncLocalStorage();

// workerd does NOT propagate AsyncLocalStorage context into
// EventTarget listeners fired by the runtime (WebSocket message/close/error,
// EventSource) — probed at compat 2024-01-01 and 2025-08-01
// (scripts/probes/read-mode-als-probe.mjs). Streams, timers, waitUntil and
// promises all inherit the store; those listeners run with an EMPTY store even
// while the request that registered them is alive. A header-less re-entry of
// the exported fetch from such a listener during a READ connection would see
// ambient=null and be granted write. Re-bind every listener to the store that
// was ambient when it was registered, so the re-entrancy clamp in _enterMode
// keeps working inside runtime-fired listeners.
//
// Patched at the choke point (EventTarget.prototype, which WebSocket and
// EventSource inherit) and PINNED non-writable/non-configurable on both
// prototypes so author code cannot delete or reassign the shadow and reach the
// unpatched method. `on<type>` assignment is covered by accessor properties
// (workerd's dispatch reads `this["on"+type]` as an own property at fire time).
// Known residual: Object.defineProperty(socket, 'onmessage', { value }) — a
// data property defined directly on the instance bypasses the accessor. A
// re-entry from there stays read unless it presents the write token (see
// fetch); this patch covers the accidental path.
// Listeners registered outside any request (no ambient store) are untouched.
(function bindRuntimeListenersToAmbientMode() {
  const ET = globalThis.EventTarget && globalThis.EventTarget.prototype;
  if (!ET || typeof ET.addEventListener !== 'function') return;
  // Idempotent: production evaluates this module once per isolate, but the
  // test pool re-evaluates it per file in one isolate. The first evaluation
  // pins; later ones must not try to redefine a non-configurable property.
  // (The marker is a capability-free boolean — knowing the patch exists grants
  // nothing.)
  const MARK = Symbol.for('vibe-coded.shim.listeners-bound');
  if (ET.addEventListener[MARK]) return;
  const origAdd = ET.addEventListener;
  const origRemove = ET.removeEventListener;
  // listener -> Map<store, bound>: the same function registered from two
  // different requests gets two wrappers, and removeEventListener resolves
  // with the ambient store so each request removes what it installed.
  const bindings = new WeakMap();
  function boundFor(listener, store) {
    let perStore = bindings.get(listener);
    if (!perStore) { perStore = new Map(); bindings.set(listener, perStore); }
    let bound = perStore.get(store);
    if (!bound) {
      const invoke = typeof listener === 'function'
        ? listener
        : (event) => listener.handleEvent(event);
      bound = function boundToAmbientMode(event) {
        return _alsRun.call(als, store, () => invoke.call(this, event));
      };
      perStore.set(store, bound);
    }
    return bound;
  }
  function addEventListenerInAmbientMode(type, listener, options) {
    const store = _alsGetStore.call(als);
    if (!store || listener === null || listener === undefined) {
      return origAdd.call(this, type, listener, options);
    }
    return origAdd.call(this, type, boundFor(listener, store), options);
  }
  function removeEventListenerInAmbientMode(type, listener, options) {
    const store = _alsGetStore.call(als);
    const perStore = listener ? bindings.get(listener) : undefined;
    const bound = store && perStore ? perStore.get(store) : undefined;
    return origRemove.call(this, type, bound || listener, options);
  }
  const pin = (target, name, value) => Object.defineProperty(target, name, {
    value, writable: false, configurable: false, enumerable: false,
  });
  Object.defineProperty(addEventListenerInAmbientMode, MARK, { value: true });
  const protos = [ET];
  if (globalThis.WebSocket && globalThis.WebSocket.prototype !== ET) protos.push(globalThis.WebSocket.prototype);
  for (const proto of protos) {
    pin(proto, 'addEventListener', addEventListenerInAmbientMode);
    pin(proto, 'removeEventListener', removeEventListenerInAmbientMode);
  }
  // `socket.onmessage = fn` etc.: an accessor on EventTarget.prototype whose
  // setter installs an instance accessor (so later assignments re-bind and
  // the runtime's own-property read at dispatch sees the bound wrapper).
  for (const name of ['onmessage', 'onclose', 'onerror', 'onopen']) {
    const install = function (fn) {
      const store = _alsGetStore.call(als);
      const value = typeof fn === 'function' && store ? boundFor(fn, store) : fn;
      Object.defineProperty(this, name, {
        get: () => value,
        set: install,
        configurable: true,
        enumerable: true,
      });
    };
    Object.defineProperty(ET, name, {
      get() { return undefined; },
      set: install,
      configurable: false,
      enumerable: false,
    });
  }
})();
let _userWorker;

const WRITE_ACCESS_DENIED = 'Write access denied: this connection has read-only access to this vibe';
const D1_ENTITLEMENT_REQUIRED = 'SQL storage (env.VIBE_D1) is unavailable for this vibe. SQL requires Pro ($9/mo) or Pro+ ($20/mo): vibe-coded.ai/pricing. Tell your agent: "use KV storage, or configure this vibe for SQL after upgrading."';

class D1EntitlementError extends Error {
  constructor() {
    super(D1_ENTITLEMENT_REQUIRED);
    this.code = 'ENTITLEMENT_EXCEEDED';
  }
}

// An uncaught D1EntitlementError would reach the platform as a generic
// "Worker execution failed", so answer it here with the platform's standard
// plan-gate body (same shape as entitlementErrorResponse).
function d1EntitlementResponse() {
  return new Response(JSON.stringify({
    success: false,
    error: D1_ENTITLEMENT_REQUIRED,
    code: 'ENTITLEMENT_EXCEEDED',
    limitType: 'd1_storage',
    upgradeUrl: 'https://vibe-coded.ai/pricing',
  }), { status: 403, headers: { 'Content-Type': 'application/json' } });
}

// A vibe without a D1 binding must fail with the plan gate, not a raw
// "Cannot read properties of undefined" exception. This is deliberately only
// a denying facade: it captures no database and can never fall back to the
// shared platform DB (INV-D1-ISOLATION-1).
function createUnavailableD1() {
  const deny = () => { throw new D1EntitlementError(); };
  return {
    prepare: deny,
    batch: deny,
    exec: deny,
    dump: deny,
    withSession: deny,
  };
}

function currentMode() {
  return _alsGetStore.call(als)?.mode ?? 'read';
}

function _constantTimeEqual(a, b) {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return diff === 0;
}

function denyReadOnlyWrite() {
  if (currentMode() !== 'write') {
    throw new Error(WRITE_ACCESS_DENIED);
  }
}

// Establish the request's access mode, then run `fn` inside it. PRIVATE and NOT
// EXPORTED — this is the only way to enter 'write', and only fetch() calls it.
// It is deliberately unreachable from user code: the shim deploys as the sibling
// module `_platform-shim.js` next to the vibe's `worker.js` in the SAME Workers
// script, so author code can `import('./_platform-shim.js')` (via a computed
// specifier that survives bundling — verified) and reach any EXPORTED symbol
// operating on this same private `als`. If a mode-setter were exported, a
// viewer's read-mode MCP call to an author-controlled tool could re-enter write
// and mutate storage. So the module exports no way
// to raise privilege; write is obtainable only through the platform-controlled
// fetch() entry below. fetch() wraps ALL user code — including the dynamic
// import of worker.js, i.e. user module top-level — inside this scope, so there
// is no reachable frame in which user code runs without a mode.
//
// CLAMP (never raise above ambient): a genuine top-level platform call has no
// ambient store and takes the requested mode. Any ambient store means we are
// re-entered from inside an existing request scope (fetch is the exported
// entrypoint, so user code can re-invoke it) — clamp to read so a read request
// can never be escalated to write. Living here, not in fetch(), makes the
// no-escalation invariant true by construction for every entrypoint (fetch
// today; scheduled/queue if ever added), not just the one that remembered it.
function _enterMode(requestedMode, fn) {
  const ambient = _alsGetStore.call(als);
  const mode = ambient?.mode === 'read' ? 'read' : requestedMode;
  // Pass the effective (clamped) mode to fn so the caller wraps bindings against
  // what was actually entered, not what it requested.
  return _alsRun.call(als, { mode }, () => fn(mode));
}

/**
 * Create a KV namespace wrapper that auto-prefixes all keys.
 * Handles double-prefix safety: if a key already starts with the prefix,
 * it is not prefixed again (protects against legacy workers that include
 * their own createStorage helper).
 *
 * @param {KVNamespace} kv - Raw KV namespace binding
 * @param {string} prefix - Key prefix (e.g., "vibe:matt--my-app:")
 * @returns {KVNamespace} Wrapped KV namespace with transparent prefixing
 */
export function createPrefixedKV(kv, prefix) {
  function safePrefix(key) {
    // Avoid double-prefixing if key already has the vibe prefix
    if (typeof key === 'string' && key.startsWith(prefix)) {
      return key;
    }
    return prefix + key;
  }

  return {
    get(key, options) {
      return kv.get(safePrefix(key), options);
    },
    put(key, value, options) {
      denyReadOnlyWrite();
      return kv.put(safePrefix(key), value, options);
    },
    delete(key) {
      denyReadOnlyWrite();
      return kv.delete(safePrefix(key));
    },
    list(options) {
      const opts = options || {};
      // Double-prefix guard: if user's prefix already starts with our prefix, don't prepend again
      const userPrefix = opts.prefix || '';
      const callerHandlesPrefixing = userPrefix.startsWith(prefix);
      const fullPrefix = callerHandlesPrefixing ? userPrefix : prefix + userPrefix;
      return kv.list({
        ...opts,
        prefix: fullPrefix
      }).then(function(result) {
        // If the caller already included our prefix (legacy createStorage pattern),
        // they handle their own key stripping — return names unchanged.
        if (callerHandlesPrefixing) {
          return result;
        }
        return {
          ...result,
          keys: result.keys.map(function(k) {
            // Defensive: only strip prefix if present
            const name = k.name.startsWith(prefix)
              ? k.name.slice(prefix.length)
              : k.name;
            return { ...k, name: name };
          })
        };
      });
    },
    getWithMetadata(key, options) {
      return kv.getWithMetadata(safePrefix(key), options);
    }
  };
}

/**
 * Read a platform-set over-quota flag from the RAW (un-prefixed) VIBE_STORAGE
 * namespace. FAIL-OPEN: any error (missing binding, KV outage) returns false so
 * a transient KV failure can never block all writes — only an explicitly-present
 * flag blocks. Shared by the R2 (`r2:overquota:`) and D1 (`d1:overquota:`) write
 * gates so the fail-open semantics stay in lockstep — one impl, one place to fix.
 * The key MUST stay byte-for-byte identical to the platform reconcile writer's
 * (r2OverQuotaKey / d1OverQuotaKey); the shim is a standalone bundle and can't
 * import it, so callers pass the literal key.
 *
 * @param {KVNamespace|undefined} kv - RAW VIBE_STORAGE namespace
 * @param {string} key - Physical flag key
 * @param {string} label - Short resource label for the warn log ("R2" | "D1")
 * @returns {Promise<boolean>} true only if the flag is explicitly present
 */
export async function readOverQuotaFlag(kv, key, label) {
  try {
    if (!kv || typeof kv.get !== 'function') return false;
    const flag = await kv.get(key);
    return flag !== null && flag !== undefined;
  } catch (err) {
    console.warn(label + ' over-quota flag read failed (allowing write)', { error: String(err) });
    return false;
  }
}

/**
 * KV facade with byte-quota enforcement.
 *
 * Wraps createPrefixedKV (vibe-scoped key prefixing) and adds a WRITE-GATE:
 * before a put(), it reads the platform-set `kv:overquota:{vibeId}` flag and
 * rejects the write if present. get / delete / list / getWithMetadata are never
 * blocked — deletes MUST stay available so a user can free space to get back
 * under quota (mirrors the D1/R2 facades).
 *
 * Reconcile-only: the facade does NOT meter bytes on the write path — KV put()
 * returns no size, so there is no per-write ground truth (unlike D1's
 * meta.size_after). vibes.kvBytesUsed is reconciled by the hourly sweep
 * (services/kv-reconcile-scheduled.ts), which also sets/clears the flag.
 *
 * The flag lives in the RAW VIBE_STORAGE namespace, un-prefixed, so vibe code —
 * which can only reach prefixed keys through this facade — cannot read or forge
 * it. FAIL-OPEN: a flag-read error allows the write (readOverQuotaFlag). The
 * check is memoized per request (the facade is rebuilt per fetch), sparing a
 * chatty write loop N KV round-trips.
 *
 * @param {KVNamespace} kv - RAW vibe KV namespace being wrapped
 * @param {string} prefix - Vibe key prefix ('vibe:{userSlug}--{vibeSlug}:')
 * @param {object} opts
 * @param {string|number} opts.vibeId - Numeric vibeId for the flag key
 * @param {KVNamespace} [opts.flagKv] - Namespace holding the flag (defaults to
 *   `kv`); pass the raw VIBE_STORAGE when wrapping a different alias (env.KV) so
 *   the flag is always read from where the sweep writes it.
 * @returns {object} KV-like facade
 */
export function createMeteredKV(kv, prefix, opts) {
  const options = opts || {};
  const base = createPrefixedKV(kv, prefix);
  const vibeId = options.vibeId != null ? String(options.vibeId) : null;
  // The flag ALWAYS lives in the raw VIBE_STORAGE namespace (where the sweep
  // writes it), which can differ from `kv` when wrapping the env.KV alias.
  const flagKv = options.flagKv || kv;
  // Per-user over-quota flag key. MUST stay byte-for-byte identical to the key the
  // platform sweep writes (kvOverQuotaKey, src/services/kv-reconcile-scheduled.ts).
  // The raw namespace is un-prefixed, so no `vibe:{slug}:` prefix here.
  const flagKey = vibeId !== null ? 'kv:overquota:' + vibeId : null;
  // Per-request memo (undefined = not yet read). Fail-open + rare off→on
  // transitions ⇒ per-request granularity is enough.
  let overQuotaFlag;

  async function isOverQuota() {
    if (flagKey === null) return false;
    if (overQuotaFlag === undefined) {
      overQuotaFlag = await readOverQuotaFlag(flagKv, flagKey, 'KV');
    }
    return overQuotaFlag;
  }

  return {
    get: function (key, getOpts) { return base.get(key, getOpts); },
    list: function (listOpts) { return base.list(listOpts); },
    getWithMetadata: function (key, gwmOpts) { return base.getWithMetadata(key, gwmOpts); },
    delete: function (key) {
      denyReadOnlyWrite();
      return base.delete(key);
    },
    put: async function (key, value, putOpts) {
      denyReadOnlyWrite();
      if (await isOverQuota()) {
        throw new Error('KV storage quota exceeded for this vibe');
      }
      return base.put(key, value, putOpts);
    },
  };
}

/**
 * Build a safe, prefixed R2 object key.
 *
 * Mirrors `R2Adapter._getKey` from src/services/r2-adapter.ts (lines 125-173).
 * The shim must be self-contained (no imports), so this is a copy. Keep in
 * sync — both implementations exist for defense-in-depth across the platform
 * (R2Adapter for in-process platform code; this wrapper for vibe workers).
 *
 * Defenses:
 * - URL-decode up to 3 times (defends `%2e%2e%2f`, `%252e...` double-encoded)
 * - Split on `/`, normalize segments (`.` collapse, `..` reject if at root)
 * - Reject Windows `\` separator inside segments
 * - Reject null bytes (path truncation attack vector)
 *
 * @param {string} prefix - The vibe's key prefix (always ends with `/`)
 * @param {string} key - User-supplied key
 * @returns {string} Fully prefixed, normalized R2 key
 * @throws {Error} If key contains traversal, null bytes, or other unsafe chars
 */
export function _r2GetKey(prefix, key) {
  if (typeof key !== 'string') {
    throw new Error('Invalid key format');
  }

  let decodedKey = key;
  for (let i = 0; i < 3; i++) {
    try {
      const next = decodeURIComponent(decodedKey);
      if (next === decodedKey) break;
      decodedKey = next;
    } catch (_e) {
      break;
    }
  }

  const segments = decodedKey.split('/');
  const safeSegments = [];
  for (const segment of segments) {
    if (segment === '' || segment === '.') continue;
    if (segment === '..') {
      if (safeSegments.length === 0) {
        throw new Error('Invalid key format');
      }
      safeSegments.pop();
      continue;
    }
    if (segment.includes('\\') || segment.includes('\0')) {
      throw new Error('Invalid key format');
    }
    safeSegments.push(segment);
  }

  const normalizedKey = safeSegments.join('/');
  // Allow empty key only when input was empty (for list-with-no-prefix calls)
  if (!normalizedKey && key !== '') {
    throw new Error('Invalid key format');
  }
  return prefix + normalizedKey;
}

/**
 * Create an R2 bucket wrapper that auto-prefixes all keys with the vibe's
 * environment-specific tree (`vibes/{vibeId}/` or `vibes-preview/{vibeId}/`).
 *
 * Production writes `vibes/123/foo`; preview writes `vibes-preview/123/foo`.
 * A constructed key cannot leave the wrapper's tree, and no vibe can reach
 * another vibe's tree. The preview/production split guards against mistakes,
 * not the owner's own code: both environments share the per-vibe token, so
 * code that calls the sign-url endpoint directly can ask for its own vibe's
 * production tree.
 *
 * Quota enforcement: `put()` (the only op that GROWS
 * usage) is rejected when the platform's hourly R2 reconcile sweep has flagged
 * this vibe's owner as over their plan's R2 limit. The flag is a cheap KV key
 * (`r2:overquota:{vibeId}`) written by the sweep into the SAME physical KV
 * namespace this worker binds as VIBE_STORAGE — so the shim can enforce with a
 * single local KV read and no platform round-trip on the hot path. Reads,
 * downloads, and DELETES are never blocked (delete lets a user free space and
 * recover). Fail-open: a KV read error never blocks the write — only an
 * explicitly-set flag does. The signed-URL path keeps its own atomic
 * `reserveR2Quota` check; this closes the binding-put hole between sweeps.
 *
 * @param {R2Bucket} bucket - Raw R2 bucket binding (VIBE_R2)
 * @param {string|number} vibeId - Numeric vibeId from the VIBE_ID binding
 * @param {object} [env] - Raw worker env; createUploadUrl/createDownloadUrl read
 *   PLATFORM_VIBE_TOKEN/PLATFORM_API_URL, and put() reads the over-quota
 *   flag from env.VIBE_STORAGE (the RAW, un-prefixed namespace).
 * @returns {object} Wrapped bucket with the same put/get/head/delete/list surface
 */
export function createPrefixedR2(bucket, vibeId, env) {
  // Strict positive-integer validation on VIBE_ID — this value is the
  // isolation boundary between vibes. If the dispatcher ever injects an
  // empty / non-numeric / negative / decimal value, the resulting prefix
  // could collapse (e.g. `vibes//` → matches all vibes) or escape via
  // path components inside the value itself. Fail loudly: better to break
  // R2 access for one vibe than to silently share storage across vibes.
  const idStr = String(vibeId);
  if (!/^[1-9]\d*$/.test(idStr)) {
    throw new Error(`Refusing to wrap VIBE_R2: invalid VIBE_ID ${JSON.stringify(vibeId)} (expected positive integer)`);
  }
  // Capture env for createUploadUrl / createDownloadUrl + the over-quota flag
  // read in put(). May be undefined in unit-test paths; each consumer guards.
  const capturedEnv = env;
  // Only the exact build-runner value "preview" opts into preview data. Missing
  // or unknown values are production so already-deployed scripts (which have no
  // VIBE_ENV binding) keep reaching their existing data.
  const environment = capturedEnv && capturedEnv.VIBE_ENV === 'preview'
    ? 'preview'
    : 'production';
  const prefix = environment === 'preview'
    ? `vibes-preview/${idStr}/`
    : `vibes/${idStr}/`;

  /**
   * Return true if the platform reconcile sweep has flagged this vibe's owner as
   * over their R2 quota. Fail-open (see `readOverQuotaFlag`). The flag KEY MUST
   * stay byte-for-byte identical to `r2OverQuotaKey()` in
   * src/services/r2-reconcile-scheduled.ts; VIBE_STORAGE is the RAW (un-prefixed)
   * namespace, so no `vibe:{slug}:` prefix.
   */
  function isOverQuota() {
    return readOverQuotaFlag(capturedEnv && capturedEnv.VIBE_STORAGE, 'r2:overquota:' + idStr, 'R2');
  }

  return {
    /**
     * Put an object. Body can be string | ArrayBuffer | ReadableStream | Blob | null.
     *
     * `async` so validation errors (path traversal, null bytes) surface as
     * a rejected promise rather than a sync throw — matching the R2Bucket
     * contract callers expect.
     *
     * Quota gate: rejects when the owner is flagged
     * over their R2 limit. Checked BEFORE key normalization so an over-quota
     * vibe is stopped regardless of key shape. Fail-open on flag-read error.
     */
    async put(key, body, options) {
      denyReadOnlyWrite();
      if (await isOverQuota()) {
        throw new Error('R2 storage quota exceeded for this vibe');
      }
      const fullKey = _r2GetKey(prefix, key);
      return bucket.put(fullKey, body, options);
    },

    /**
     * Get an object. Returns `R2ObjectBody | null`.
     */
    async get(key, options) {
      const fullKey = _r2GetKey(prefix, key);
      return bucket.get(fullKey, options);
    },

    /**
     * Get object metadata without body. Returns `R2Object | null`.
     */
    async head(key) {
      const fullKey = _r2GetKey(prefix, key);
      return bucket.head(fullKey);
    },

    /**
     * Delete one or more objects. Accepts string or string[].
     */
    async delete(keys) {
      denyReadOnlyWrite();
      if (Array.isArray(keys)) {
        return bucket.delete(keys.map(function(k) { return _r2GetKey(prefix, k); }));
      }
      return bucket.delete(_r2GetKey(prefix, keys));
    },

    /**
     * List objects under the vibe's prefix.
     *
     * Caller may pass an additional `prefix` in options — this is APPENDED
     * to the vibe prefix, never replaces it. Returned object keys have the
     * vibe prefix STRIPPED so callers see only their relative paths.
     */
    async list(options) {
      const opts = options || {};
      // Defensive: if caller's prefix already starts with our vibe prefix,
      // they're handling stripping themselves (legacy R2Adapter pattern) —
      // pass through unchanged.
      const userPrefix = opts.prefix || '';
      const callerHandlesPrefixing = userPrefix.startsWith(prefix);
      const fullPrefix = callerHandlesPrefixing ? userPrefix : prefix + userPrefix;
      const result = await bucket.list({ ...opts, prefix: fullPrefix });
      if (callerHandlesPrefixing) {
        return result;
      }
      return {
        ...result,
        objects: (result.objects || []).map(function(obj) {
          const name = obj.key && obj.key.startsWith(prefix)
            ? obj.key.slice(prefix.length)
            : obj.key;
          // Return a shallow copy with key replaced — preserve etag/size/etc
          return { ...obj, key: name };
        }),
      };
    },

    /**
     * Mint a presigned PUT URL for browser direct-upload to R2.
     *
     * The browser PUTs bytes directly to R2 — bypasses the worker entirely
     * (no 100MB CPU/memory ceiling, no proxy latency).
     *
     * @param {string} key - User-supplied key (auto-namespaced to vibes/{vibeId}/key)
     * @param {object} opts - REQUIRED. Must include `contentLength`.
     * @param {number} opts.contentLength - REQUIRED. EXACT byte size of the upload
     *   (pass `file.size`). It is pinned into the signature — R2 rejects a PUT of any
     *   other size — and reserved against your R2 quota. The client must then send
     *   `Content-Length: <contentLength>` on the PUT. Uploads without it are rejected
     *   (the platform returns 400): an unpinned PUT URL would let a client store up to
     *   R2's 5 GiB single-PUT limit regardless of the reserve.
     * @param {string} [opts.contentType] - Hint for the upload's Content-Type header
     * @param {number} [opts.maxSize] - Deprecated and IGNORED. A loose bound cannot be
     *   pinned into the signature, so it does not bound the upload. Use `contentLength`.
     * @param {number} [opts.ttl=300] - URL lifetime in seconds (max 3600 = 1 hour)
     * @returns {Promise<{ url: string, expiresAt: number }>}
     */
    async createUploadUrl(key, opts) {
      denyReadOnlyWrite();
      const options = opts || {};
      // Fail fast with an actionable message instead of an opaque HTTP 400 from
      // the platform sign-url endpoint (which rejects a missing/non-numeric size
      // and surfaces as a 500 to the vibe's end user).
      if (options.contentLength == null) {
        throw new Error('VIBE_R2.createUploadUrl: opts.contentLength (number, bytes) is required');
      }
      const fullKey = _r2GetKey(prefix, key);
      return _signR2Url(capturedEnv, {
        vibeId: idStr,
        environment: environment,
        key: fullKey,
        mode: 'upload',
        ttl: options.ttl || 300,
        maxSize: options.maxSize,
        contentLength: options.contentLength,
        contentType: options.contentType,
      });
    },

    /**
     * Mint a presigned GET URL for browser direct-download from R2.
     *
     * Use this to serve images / files to the browser without proxying
     * bytes through your worker — `<img src={url} />` works directly.
     *
     * @param {string} key - User-supplied key (auto-namespaced to vibes/{vibeId}/key)
     * @param {object} [opts]
     * @param {number} [opts.ttl=3600] - Requested URL lifetime in seconds. NOTE:
     *   the platform clamps download URLs to 120s server-side (presigned GETs are
     *   meant for an immediate fetch, not long-lived links), so values above 120
     *   are silently capped. The 3600 default is accepted and clamped to 120.
     * @returns {Promise<{ url: string, expiresAt: number }>}
     */
    async createDownloadUrl(key, opts) {
      const options = opts || {};
      const fullKey = _r2GetKey(prefix, key);
      return _signR2Url(capturedEnv, {
        vibeId: idStr,
        environment: environment,
        key: fullKey,
        mode: 'download',
        ttl: options.ttl || 3600,
      });
    },
  };
}

// ===========================================================================
// D1 storage-byte metering
// ===========================================================================
//
// A paid-plan vibe's worker talks to its OWN dedicated D1 database via
// env.VIBE_D1 — a database the platform cannot reach to meter (no CF HTTP API
// by design). Without a wrapper here, that binding path has NO storage cap:
// a paying user could max out their per-vibe DB (and repeat across accounts)
// as unbounded storage. This facade closes that hole using D1's own accounting.
//
// Ground truth is `D1Result.meta.size_after` — the whole-database size in bytes
// returned on every executed statement. For a DEDICATED database that IS the
// vibe's total, so the facade has a byte-accurate reading with zero extra
// queries and zero external calls. It enforces INLINE on the local ground
// truth (tighter than the R2 reconcile pattern, which needs an out-of-band
// sweep because the platform CAN measure the shared R2 bucket but CANNOT
// measure a dedicated D1 DB).
//
// Two-layer model:
//   1. Per-vibe cap — enforced locally via size_after (real-time, no round-trip).
//   2. Per-user cap — only the platform can sum a user's vibes, so it sets a
//      `d1:overquota:{vibeId}` KV flag (mirrors R2's `r2:overquota:{vibeId}`);
//      this facade checks it fail-open, exactly like the R2 put() gate.
//
// Enforcement is applied ONLY when the DB is dedicated (D1_DEDICATED === '1');
// the shared-DB path stays platform-metered. Reads and recovery verbs
// (DELETE/DROP/VACUUM) are always allowed so an over-cap vibe can shrink back
// under. Growth verbs (INSERT/UPDATE/CREATE/…) are rejected when over cap.

/**
 * Leading D1/SQLite keywords that CANNOT grow storage — reads + the recovery
 * verbs a stuck-over-cap vibe needs to free space. Everything else is treated
 * as growth (fail closed). This is a COARSE quota hint, NOT an isolation
 * boundary: evading it only lets a vibe write to its OWN database past its cap
 * (bounded by Cloudflare's 10 GB per-DB hard limit) — never a cross-tenant
 * effect. So the check is deliberately cheap (leading-keyword only) rather than
 * a full SQL parser. UPDATE is conservatively classed as growth even though it
 * can shrink; an over-cap vibe uses DELETE/DROP/VACUUM to recover.
 */
const D1_NON_GROWTH_KEYWORDS = new Set([
  'SELECT', 'DELETE', 'DROP', 'VACUUM', 'PRAGMA', 'EXPLAIN', 'ANALYZE',
  'REINDEX', 'DETACH', 'BEGIN', 'COMMIT', 'END', 'ROLLBACK', 'SAVEPOINT',
  'RELEASE',
]);

/**
 * Return `sql`'s leading SQL keyword (upper-cased), skipping leading whitespace
 * and line (`-- …`) / block (`/* … *\/`) comments so a comment prefix cannot
 * disguise the verb. Returns null for non-string / empty / non-alpha-leading
 * input (callers treat null as fail-closed). Shared by both classifiers so verb
 * extraction has one implementation.
 * @param {string} sql
 * @returns {string|null}
 */
function _leadingVerb(sql) {
  const s = _stripLeadingComments(sql);
  if (s === null) return null;
  const m = s.match(/^([a-zA-Z]+)/);
  return m ? m[1].toUpperCase() : null;
}

/**
 * Strip leading whitespace + line (`-- …`) / block (`/* … *\/`) comments,
 * repeatedly (a statement may start with several stacked comments). Bounded
 * loop — never trust a single pass. The single implementation behind every
 * SQL classifier in this file. Returns null for non-string input.
 * @param {string} sql
 * @returns {string|null}
 */
function _stripLeadingComments(sql) {
  if (typeof sql !== 'string') return null;
  let s = sql;
  for (let i = 0; i < 100; i++) {
    const before = s;
    s = s.replace(/^\s+/, '');
    if (s.startsWith('--')) {
      const nl = s.indexOf('\n');
      s = nl === -1 ? '' : s.slice(nl + 1);
    } else if (s.startsWith('/*')) {
      const end = s.indexOf('*/');
      s = end === -1 ? '' : s.slice(end + 2);
    }
    if (s === before) break;
  }
  return s;
}

/**
 * Idempotent schema bootstrap that a READ-mode caller may issue as a no-op:
 * `CREATE TABLE IF NOT EXISTS` and
 * `CREATE [UNIQUE] INDEX IF NOT EXISTS`. Template- and builder-built vibes
 * call _ensureTable() at the top of EVERY tool, reads included; denying it in
 * read mode would leave viewers and public callers unable to call any tool. On a
 * readable vibe the object already exists, so skipping the statement changes
 * nothing; if it does not exist, the read that follows fails honestly ("no
 * such table"). Nothing else is exempt: plain CREATE, TEMP, VIEW, TRIGGER,
 * ALTER and every mutation still require write access.
 * @param {string} sql
 * @returns {boolean}
 */
export function _isIdempotentSchemaDdl(sql) {
  const s = _stripLeadingComments(sql);
  return s !== null && /^CREATE\s+(TABLE|UNIQUE\s+INDEX|INDEX)\s+IF\s+NOT\s+EXISTS\b/i.test(s);
}

/** What a read-mode caller gets back for an idempotent DDL no-op. */
function _readModeDdlNoopResult() {
  return { success: true, results: [], meta: { changes: 0, rows_read: 0, rows_written: 0, duration: 0, last_row_id: 0 } };
}

/**
 * True if `sql`'s leading keyword indicates a statement that could grow storage.
 * Unknown / empty / non-string / CTE (`WITH …`) leading verbs → true (fail
 * closed). Exported for direct unit testing.
 * @param {string} sql
 * @returns {boolean}
 */
export function _isD1GrowthStatement(sql) {
  const verb = _leadingVerb(sql);
  return verb === null || !D1_NON_GROWTH_KEYWORDS.has(verb);
}

/**
 * Return true only for statements that are safe in read mode. This allowlist is
 * intentionally narrower than D1_NON_GROWTH_KEYWORDS: recovery and control
 * verbs still mutate database state and therefore require write access.
 *
 * @param {string} sql
 * @returns {boolean}
 */
export function _isD1ReadStatement(sql) {
  const verb = _leadingVerb(sql);
  return verb === 'SELECT' || verb === 'EXPLAIN';
}

/**
 * Wrap a dedicated per-vibe D1 database binding with storage-byte quota
 * enforcement. See the section header above for the model.
 *
 * @param {D1Database} db - Raw dedicated VIBE_D1 binding
 * @param {object} opts
 * @param {number} [opts.capBytes] - Per-vibe byte ceiling. If not a positive
 *   number, the facade METERS but never blocks locally (transitional: e.g. a
 *   partial binding rollout) — the per-user KV flag still applies.
 * @param {string|number} opts.vibeId - Numeric vibeId (for the over-quota flag key)
 * @param {object} [opts.env] - Raw worker env; `env.VIBE_STORAGE` (the RAW,
 *   un-prefixed namespace) is read for the per-user over-quota flag, and
 *   `env.PLATFORM_VIBE_TOKEN` authenticates usage reports.
 * @param {object} [opts.ctx] - Execution context; usage reports run via
 *   `ctx.waitUntil` (fire-and-forget, off the request's critical path).
 * @returns {D1Database} Wrapped binding with the same prepare/batch/exec/dump/withSession surface
 */
export function createMeteredD1(db, opts) {
  const options = opts || {};
  const cap = (typeof options.capBytes === 'number' && options.capBytes > 0)
    ? options.capBytes
    : Infinity;
  const vibeId = String(options.vibeId);
  const capturedEnv = options.env;
  // Execution context — used for fire-and-forget usage reports via waitUntil so
  // they never add latency to (or get cancelled with) the vibe's request.
  const ctx = options.ctx;
  // Per-user over-quota flag key. MUST stay byte-for-byte identical to the key
  // the platform reconcile writes (d1OverQuotaKey, src/routes/api/internal/d1-usage.ts).
  // VIBE_STORAGE is the RAW namespace, so no prefix.
  const flagKey = 'd1:overquota:' + vibeId;
  // Only report a usage delta once it moves this much — bounds report subrequests
  // on chatty write loops (one report per request minimum, then per ~64KB growth).
  const REPORT_THRESHOLD_BYTES = 64 * 1024;

  // Local ground truth: whole-DB bytes as last reported by meta.size_after.
  // null until the facade has seen a result (or a probe).
  let lastKnownBytes = null;
  // Last size we reported to the platform this request (null = none yet).
  let lastReportedBytes = null;
  // Per-request memo of the over-quota flag (undefined = not yet read). The
  // wrapper is request-scoped (rebuilt per fetch), so caching one read spares a
  // chatty write loop N KV round-trips — the flag transitions off→on rarely and
  // the check is fail-open, so per-request granularity is enough.
  let overQuotaFlag;

  // Report the current whole-DB size to the platform (per-user aggregate +
  // honest usage numbers). Fire-and-forget via
  // waitUntil; debounced so reads and tiny writes don't spam subrequests. Called
  // only from WRITE paths — reads don't change the DB size.
  function maybeReport(size) {
    if (!ctx || typeof ctx.waitUntil !== 'function') return;
    if (!capturedEnv || !capturedEnv.PLATFORM_VIBE_TOKEN) return;
    if (typeof size !== 'number' || size < 0) return;
    if (lastReportedBytes !== null && Math.abs(size - lastReportedBytes) < REPORT_THRESHOLD_BYTES) return;
    const previous = lastReportedBytes;
    lastReportedBytes = size;
    // RE-ARM on failure: sizeAfter is an absolute level, so a
    // shed/failed report only heals via a LATER report — and the byte-delta
    // debounce would suppress that retry if we kept the optimistic marker.
    // Restoring the previous marker makes the NEXT write re-attempt, so
    // staleness is bounded by rate-limit-window-or-quiescence (and a
    // quiescent DB isn't growing).
    ctx.waitUntil(_reportD1Usage(capturedEnv, vibeId, size).then(function (ok) {
      if (!ok) lastReportedBytes = previous;
    }));
  }

  function absorb(result, isWrite) {
    const size = result && result.meta && result.meta.size_after;
    if (typeof size === 'number' && size >= 0) {
      lastKnownBytes = size;
      if (isWrite) maybeReport(size);
    }
  }

  // Cold-start guard: if we've never seen a size, probe once with a cheap read
  // so an already-over-cap database is caught on the FIRST growth write rather
  // than after it. Fail-open: a probe error leaves bytes unknown (allow). Skipped
  // entirely in meter-only mode (cap === Infinity) — the probe's result could
  // never make `localOver` true there, so it would be a wasted round-trip.
  async function ensureSizeKnown() {
    if (cap === Infinity || lastKnownBytes !== null) return;
    try {
      const probe = await db.prepare('SELECT 1').all();
      absorb(probe, false); // read: refresh size, don't trigger a usage report
    } catch (_e) {
      // Leave unknown — never let a probe failure break writes.
    }
  }

  // Per-user layer: FAIL-OPEN read of the platform-set flag (mirrors R2). Memoized
  // for the request lifetime (see overQuotaFlag above).
  async function isOverQuotaFlag() {
    if (overQuotaFlag === undefined) {
      overQuotaFlag = await readOverQuotaFlag(capturedEnv && capturedEnv.VIBE_STORAGE, flagKey, 'D1');
    }
    return overQuotaFlag;
  }

  // Throw if we're over either cap. No classification — callers decide whether
  // the operation can grow storage before invoking this.
  async function enforceIfOverCap() {
    await ensureSizeKnown();
    const localOver = lastKnownBytes !== null && lastKnownBytes >= cap;
    if (localOver || await isOverQuotaFlag()) {
      throw new Error('D1 storage quota exceeded for this vibe');
    }
  }

  // Map each wrapped statement → { realStmt, isRead, isGrowth }. A WeakMap (not
  // a property on the wrapper) so a vibe CANNOT forge a statement that unwraps
  // to an arbitrary real statement while presenting read-shaped SQL: a
  // symbol property would be liftable via Object.getOwnPropertySymbols and let
  // batch() run an INSERT while classifying it as a SELECT. Foreign objects
  // aren't in this map, so batch() treats them as unknown (→ growth + non-read,
  // fail closed) and passes them through raw (the real D1 binding then rejects
  // non-statements).
  const wrapperMeta = new WeakMap();

  function wrapStatement(realStmt, sql, flags) {
    // Classify the immutable SQL ONCE at wrap time (it can't change after
    // prepare()); only the access MODE is call-time state, checked inside
    // denyReadOnlyWrite() via ALS on every invocation.
    const { isRead, isGrowth, isIdempotentDdl } = flags || {
      isRead: _isD1ReadStatement(sql),
      isGrowth: _isD1GrowthStatement(sql),
      isIdempotentDdl: _isIdempotentSchemaDdl(sql),
    };
    // Read-mode gate. Idempotent schema DDL short-circuits to a no-op result
    // instead of a denial; everything else non-read is denied.
    // Returns true when the caller should return the no-op result.
    const readModeNoop = () => {
      if (isRead) return false;
      if (isIdempotentDdl && currentMode() !== 'write') return true;
      denyReadOnlyWrite();
      return false;
    };
    const wrapped = {
      _sql: sql, // for debugging/tests only — NOT trusted for classification
      bind(...args) {
        return wrapStatement(realStmt.bind(...args), sql, { isRead, isGrowth, isIdempotentDdl });
      },
      async run() {
        if (readModeNoop()) return _readModeDdlNoopResult();
        if (isGrowth) await enforceIfOverCap();
        const r = await realStmt.run();
        absorb(r, true); // write: refresh size + maybe report to platform
        return r;
      },
      async all() {
        if (readModeNoop()) return _readModeDdlNoopResult();
        if (isGrowth) await enforceIfOverCap();
        const r = await realStmt.all();
        absorb(r, false); // .all() is typically a read; don't trigger a report
        return r;
      },
      async first(colName) {
        if (readModeNoop()) return null;
        if (isGrowth) await enforceIfOverCap();
        return realStmt.first(colName);
      },
      async raw(rawOpts) {
        if (readModeNoop()) return [];
        if (isGrowth) await enforceIfOverCap();
        return realStmt.raw(rawOpts);
      },
    };
    wrapperMeta.set(wrapped, { realStmt, isRead, isGrowth, isIdempotentDdl });
    return wrapped;
  }

  function buildSurface(target) {
    return {
      prepare(sql) {
        return wrapStatement(target.prepare(sql), sql);
      },
      async batch(statements) {
        const list = Array.isArray(statements) ? statements : [];
        // Unwrap + classify STRICTLY from our own WeakMap — never from an
        // attacker-controllable `_sql` property. A statement not minted by this
        // facade has unknown classification (→ growth + non-read, fail closed)
        // and is passed through as-is (real D1 rejects non-statements).
        const metas = list.map(function (s) { return wrapperMeta.get(s); });
        if (currentMode() !== 'write') {
          // Read mode (shim v4): idempotent schema DDL inside a batch
          // is a no-op exactly as it is for a single prepared statement —
          // a vibe may bootstrap several tables in one batch(). Any
          // statement that is neither a read nor idempotent DDL, or that this
          // facade did not mint, denies the whole batch. Reads still execute,
          // in order; the DDL slots get the synthetic no-op result.
          if (metas.some(function (meta) { return !meta || (!meta.isRead && !meta.isIdempotentDdl); })) {
            denyReadOnlyWrite();
          }
          const results = new Array(list.length);
          const readIdx = [];
          metas.forEach(function (meta, i) {
            if (meta.isRead) readIdx.push(i);
            else results[i] = _readModeDdlNoopResult();
          });
          if (readIdx.length) {
            const readResults = await target.batch(readIdx.map(function (i) { return metas[i].realStmt; }));
            readIdx.forEach(function (i, j) { results[i] = readResults[j]; });
          }
          return results;
        }
        if (metas.some(function (meta) { return !meta || !meta.isRead; })) {
          denyReadOnlyWrite();
        }
        if (metas.some(function (meta) { return !meta || meta.isGrowth; })) {
          await enforceIfOverCap();
        }
        const reals = list.map(function (s, i) {
          return metas[i] ? metas[i].realStmt : s;
        });
        const results = await target.batch(reals);
        if (Array.isArray(results) && results.length) {
          absorb(results[results.length - 1], true); // batch is a write path
        }
        return results;
      },
      async exec(sql) {
        // exec() is multi-statement and returns no size_after — we can't reliably
        // classify or meter it, so treat it as growth unconditionally: blocked
        // when over cap (an over-cap vibe recovers via prepare().run() DELETE/
        // DROP), allowed otherwise. Fail closed rather than gate on the leading
        // keyword only (which `SELECT 1; INSERT …` would slip past).
        denyReadOnlyWrite();
        await enforceIfOverCap();
        return target.exec(sql);
      },
      dump(...args) {
        return target.dump(...args);
      },
      withSession(constraint) {
        // A D1 session shares this facade's cap/size state (same physical DB).
        return buildSurface(target.withSession(constraint));
      },
    };
  }

  return buildSurface(db);
}

/**
 * POST a body to a platform /api/internal/* endpoint, authenticated with the
 * per-vibe BEARER token. Shared by `_signR2Url` and
 * `_reportD1Usage`. The token is `HMAC(master, vibeId)` minted by the
 * build-runner and injected as `PLATFORM_VIBE_TOKEN` — the master never enters
 * this isolate, and NO crypto runs here (nothing for a monkey-patched
 * crypto.subtle to intercept). The platform verifies the bearer against
 * `HMAC(master, x-vibe-id)`; the token is scoped to this one vibeId, so a leak
 * only lets the vibe act as itself.
 *
 * @param {object} env - Worker env (must have PLATFORM_VIBE_TOKEN)
 * @param {string|number} vibeId - This vibe's id (echoed as x-vibe-id)
 * @param {string} path - Internal path, e.g. '/api/internal/d1-usage'
 * @param {string} bodyJson - Pre-serialized JSON body
 * @returns {Promise<Response>} The raw fetch Response (caller handles status)
 */
export async function _signedInternalFetch(env, vibeId, path, bodyJson) {
  if (!env || !env.PLATFORM_VIBE_TOKEN) {
    throw new Error('PLATFORM_VIBE_TOKEN not configured on this worker');
  }
  // The host in the URL is only used by the platform's parseContext to route
  // this as a platform-internal call (apex host, NOT a vibe subdomain, or it'd
  // be dispatched back to a vibe).
  const url = (env.PLATFORM_API_URL || 'https://vibe-coded.ai').replace(/\/$/, '') + path;
  const init = {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-vibe-id': String(vibeId),
      'Authorization': 'Bearer ' + env.PLATFORM_VIBE_TOKEN,
    },
    body: bodyJson,
  };
  // Prefer the PLATFORM_SERVICE binding: a vibe worker CANNOT
  // reach the platform via its public hostname — same-zone routing times out
  // (HTTP 522). A service binding is direct worker-to-worker. The plain fetch
  // is the fallback for a vibe deployed without the binding (it still 522s).
  if (env.PLATFORM_SERVICE && typeof env.PLATFORM_SERVICE.fetch === 'function') {
    return env.PLATFORM_SERVICE.fetch(url, init);
  }
  return fetch(url, init);
}

/**
 * Report a dedicated D1 database's whole size (meta.size_after) to the platform
 * so it can enforce the per-USER maxD1StorageMB aggregate cap.
 * Fire-and-forget: called via ctx.waitUntil, swallows all errors —
 * a failed report must never break the vibe's request. The per-VIBE cap is still
 * enforced inline by the facade regardless of whether this report lands.
 *
 * @param {object} env - Worker env (PLATFORM_VIBE_TOKEN, VIBE_ENV)
 * @param {string|number} vibeId
 * @param {number} sizeAfter - Whole-DB bytes
 */
export async function _reportD1Usage(env, vibeId, sizeAfter) {
  try {
    // Name the database the size describes: a preview worker is bound to the
    // vibe's preview database. Missing/unknown
    // VIBE_ENV is production, matching the KV/R2 selection.
    const environment = env && env.VIBE_ENV === 'preview' ? 'preview' : 'production';
    const res = await _signedInternalFetch(env, vibeId, '/api/internal/d1-usage', JSON.stringify({ sizeAfter, environment }));
    if (!res.ok) {
      console.warn('D1 usage report rejected', { status: res.status });
      return false;
    }
    return true;
  } catch (err) {
    console.warn('D1 usage report failed', { error: String(err) });
    return false;
  }
}

/**
 * Call the platform's /api/internal/r2-sign-url endpoint (per-vibe bearer auth)
 * and return the resulting presigned R2 URL.
 *
 * @param {object} env - Worker env (must have PLATFORM_VIBE_TOKEN)
 * @param {object} body - { vibeId, environment, key, mode, ttl, maxSize?, contentLength?, contentType? }
 * @returns {Promise<{ url, expiresAt }>}
 */
export async function _signR2Url(env, body) {
  if (!env || !env.PLATFORM_VIBE_TOKEN) {
    throw new Error('VIBE_R2.createUploadUrl/createDownloadUrl unavailable: PLATFORM_VIBE_TOKEN not configured on this worker');
  }
  const bodyJson = JSON.stringify({
    environment: body.environment,
    key: body.key,
    mode: body.mode,
    ttl: body.ttl,
    maxSize: body.maxSize,
    contentLength: body.contentLength,
    contentType: body.contentType,
  });

  const res = await _signedInternalFetch(env, body.vibeId, '/api/internal/r2-sign-url', bodyJson);
  if (!res.ok) {
    // Surface the platform's error envelope verbatim — useful for quota 402s
    // and 401 stale-signature debugging.
    let errBody;
    try { errBody = await res.text(); } catch (_) { errBody = '(no body)'; }
    throw new Error('R2 signing failed: HTTP ' + res.status + ' — ' + errBody);
  }
  const parsed = await res.json();
  // Platform returns { success: true, url, expiresAt } (flat shape per
  // successResponse() convention — spreads fields onto the envelope).
  if (parsed && parsed.success && typeof parsed.url === 'string') {
    return { url: parsed.url, expiresAt: parsed.expiresAt };
  }
  throw new Error('R2 signing failed: unexpected response shape');
}

// Read-mode env is default-deny: deploy-time user variables are secrets unless
// they are one of the platform-owned CONFIG values documented here. Storage
// BINDINGS are deliberately NOT listed — in read mode they can only enter the
// env via the explicit facade assignments in fetch below, so a raw binding can
// never leak through this copy (buildWorkerBindings in cf-api.ts is the full
// inventory of what the platform attaches; it adds no asset/static binding).
const READ_ENV_ALLOWLIST = new Set([
  'USER_SLUG',       // Build-runner identity text used to derive the KV prefix.
  'VIBE_SLUG',       // Build-runner identity text used to derive the KV prefix.
  'VIBE_ID',         // Build-runner identity text used for R2/quota isolation.
  'VIBE_ENV',        // Build-runner environment selector for KV/R2 isolation.
  'D1_DEDICATED',    // Build-runner marker selecting dedicated-D1 metering.
  'D1_MAX_BYTES',    // Build-runner dedicated-D1 byte cap.
  'PLATFORM_API_URL', // Platform endpoint override used by signed wrapper calls.
]);

function createReadModeEnv(env) {
  const result = {};
  for (const key of READ_ENV_ALLOWLIST) {
    if (key in env) result[key] = env[key];
  }
  return result;
}

export default {
  async fetch(request, env, ctx) {
    const headerMode = request.headers.get('x-vibe-access-mode');
    const presented = request.headers.get('x-vibe-access-token');
    const expected = env.PLATFORM_VIBE_TOKEN;
    const proven = headerMode === 'write' && typeof expected === 'string' && expected.length > 0
      && typeof presented === 'string' && _constantTimeEqual(presented, expected);
    const requestedMode = proven ? 'write' : 'read';

    // The proof is a platform capability, not author-visible request metadata.
    // Cloning with new headers preserves the body stream without consuming it.
    const userHeaders = new Headers(request.headers);
    userHeaders.delete('x-vibe-access-token');
    const userRequest = new Request(request, { headers: userHeaders });

    // `_enterMode` clamps this against the ambient mode (so a user re-entry of
    // this exported handler during a read request cannot escalate to write) and
    // passes the effective mode to the callback. See _enterMode.
    return _enterMode(requestedMode, async (mode) => {
    // Lazy so shim module init (ALS + prototype capture above) runs before any
    // user top-level code; cache the RESOLVED handler so steady-state requests
    // skip the await entirely (the module registry already caches the import).
    const userWorker = _userWorker ??= (await import('./worker.js')).default;
    // Create a shallow copy of env to avoid mutating the original
    const wrappedEnv = mode === 'read' ? createReadModeEnv(env) : { ...env };

    // Wrap KV with key prefixing + byte-quota enforcement.
    // With VIBE_ID we use the metered facade (prefixing + the kv:overquota flag
    // write-gate); without it we can't key the flag, so fall back to prefix-only.
    if (env.VIBE_STORAGE && env.USER_SLUG && env.VIBE_SLUG) {
      // Only exact "preview" selects preview data. Missing/unknown stays on the
      // production prefix, so scripts deployed without VIBE_ENV keep their data.
      const kvPrefix = 'vibe:' + env.USER_SLUG + '--' + env.VIBE_SLUG
        + (env.VIBE_ENV === 'preview' ? '~preview:' : ':');
      wrappedEnv.VIBE_STORAGE = env.VIBE_ID
        ? createMeteredKV(env.VIBE_STORAGE, kvPrefix, { vibeId: env.VIBE_ID })
        : createPrefixedKV(env.VIBE_STORAGE, kvPrefix);

      // Also wrap KV alias if the worker uses env.KV. The flag lives in the raw
      // VIBE_STORAGE namespace, so pass it explicitly as flagKv.
      if (env.KV) {
        wrappedEnv.KV = env.VIBE_ID
          ? createMeteredKV(env.KV, kvPrefix, { vibeId: env.VIBE_ID, flagKv: env.VIBE_STORAGE })
          : createPrefixedKV(env.KV, kvPrefix);
      }

      // Atomic record-ID allocation hook. KV has no
      // compare-and-swap, so WorkerStorageAdapter's read-modify-write nextId
      // loses updates under concurrent cross-colo inserts (both writers read
      // the same id; the second record overwrites the first). The adapter
      // calls this hook when present and the per-vibe VibeStorageDO serializes
      // allocation via /api/internal/allocate-ids (per-vibe bearer auth).
      // Absent VIBE_ID/PLATFORM_VIBE_TOKEN (local dev), the adapter falls back
      // to the KV counter.
      // PLATFORM_SERVICE is REQUIRED too: without the service
      // binding, _signedInternalFetch falls back to the public hostname which
      // same-zone 522s/hangs — that would stall every insert on the hot path
      // before the adapter's catch could fall back to KV. Builds
      // without the binding simply keep the KV counter.
      if (env.VIBE_ID && env.PLATFORM_VIBE_TOKEN
          && env.PLATFORM_SERVICE && typeof env.PLATFORM_SERVICE.fetch === 'function') {
        const allocateIds = async function (table, count, seedFloor) {
          denyReadOnlyWrite();
          const res = await _signedInternalFetch(
            env,
            env.VIBE_ID,
            '/api/internal/allocate-ids',
            JSON.stringify({ table: table, count: count, seedFloor: seedFloor })
          );
          if (!res.ok) {
            const err = new Error('allocate-ids failed: HTTP ' + res.status);
            if (res.status === 429) {
              // Structured marker (NOT message matching): the adapter must
              // FAIL CLOSED on rate-limit — falling back to the racy KV
              // counter under high concurrency is the exact bug the
              // allocator exists to prevent.
              err.code = 'RATE_LIMITED';
            }
            throw err;
          }
          const parsed = await res.json();
          if (parsed && parsed.success && typeof parsed.startId === 'number') {
            return { startId: parsed.startId, count: parsed.count };
          }
          throw new Error('allocate-ids failed: unexpected response shape');
        };
        const resetIdCounter = async function (table) {
          denyReadOnlyWrite();
          const res = await _signedInternalFetch(
            env,
            env.VIBE_ID,
            '/api/internal/allocate-ids',
            JSON.stringify({ table: table, reset: true })
          );
          if (!res.ok) {
            throw new Error('reset-id-counter failed: HTTP ' + res.status);
          }
        };
        wrappedEnv.VIBE_STORAGE._allocateIds = allocateIds;
        wrappedEnv.VIBE_STORAGE._resetIdCounter = resetIdCounter;
        if (wrappedEnv.KV) {
          wrappedEnv.KV._allocateIds = allocateIds;
          wrappedEnv.KV._resetIdCounter = resetIdCounter;
        }
      }
    }
    // No else branch for read mode: createReadModeEnv starts from the config
    // allowlist, so an unwrappable binding is simply never copied in — the
    // facade assignments above are the ONLY way storage enters a read-mode env.

    // D1 metering. Isolation is handled by giving each
    // paid-plan vibe its OWN database, but isolation is NOT a storage cap: the
    // dedicated DB is one forgotten check from being used as unbounded storage.
    // When the DB is dedicated (D1_DEDICATED === '1'), wrap the binding so every
    // write is metered against the plan byte cap via meta.size_after. The
    // shared-DB path (free / non-D1 vibes) is left RAW — it's metered by the
    // platform's own D1 adapter, and size_after there is all tenants' bytes.
    // Pass the RAW env so the over-quota flag is read from the un-prefixed
    // VIBE_STORAGE namespace (same convention as the R2 wrapper below).
    if (env.VIBE_D1 && env.D1_DEDICATED === '1' && env.VIBE_ID) {
      const capBytes = env.D1_MAX_BYTES ? parseInt(env.D1_MAX_BYTES, 10) : NaN;
      wrappedEnv.VIBE_D1 = createMeteredD1(env.VIBE_D1, {
        capBytes: Number.isFinite(capBytes) ? capBytes : undefined,
        vibeId: env.VIBE_ID,
        env,
        ctx,
      });
    } else if (env.VIBE_D1 && !(env.PLATFORM_SERVICE && typeof env.PLATFORM_SERVICE.fetch === 'function')) {
      // Local `vibe dev` only: Miniflare's own per-project DB, never shared.
      // Platform deploys always carry the PLATFORM_SERVICE binding, so a
      // non-dedicated binding there falls through to the unavailable facade
      // below instead of reopening the shared platform DB (INV-D1-ISOLATION-1).
      // Wrap in BOTH modes — a raw binding could be stashed in a module global
      // during a write request and replayed ungated in a later read-mode
      // request. Empty opts: no cap probe, no over-quota flag, no usage reports.
      wrappedEnv.VIBE_D1 = createMeteredD1(env.VIBE_D1, {});
    } else {
      wrappedEnv.VIBE_D1 = createUnavailableD1();
    }

    // R2 is a shared bucket; the wrapper below namespaces all keys under
    // the environment-specific vibe tree and applies path-traversal guards.
    // Workers reach R2 only through this binding; there is no HTTP route for it.
    if (env.VIBE_R2 && env.VIBE_ID) {
      // Pass env so createUploadUrl / createDownloadUrl can find
      // PLATFORM_VIBE_TOKEN + PLATFORM_API_URL when called by user code.
      wrappedEnv.VIBE_R2 = createPrefixedR2(env.VIBE_R2, env.VIBE_ID, env);
    }

    // Don't hand the platform auth material to user code (defense-in-depth).
    // - PLATFORM_VIBE_TOKEN is the per-vibe bearer the shim's wrappers use to
    //   call /api/internal/*. Those wrappers capture the RAW
    //   `env` in their closures, so they keep working after this delete. The
    //   token is scoped to THIS vibeId, so a leak would only let the vibe act as
    //   itself — but user code has no reason to read it, so we strip it.
    // - PLATFORM_INTERNAL_SECRET (the master) is never injected into vibe
    //   workers (build-runner injects the per-vibe token instead); the
    //   delete is defensive, in case any path ever injects it.
    // Nothing in this isolate signs with a master secret (no crypto.subtle
    // call carries one), so a monkey-patched crypto has nothing to disclose.
    delete wrappedEnv.PLATFORM_VIBE_TOKEN;
    delete wrappedEnv.PLATFORM_INTERNAL_SECRET;
    // Also strip the platform service binding. The shim's own
    // wrappers use it via the captured RAW env; user code must NOT get a direct
    // worker-to-worker line to the platform (it would bypass edge protections
    // like rate limiting and reach internal routes without going through the
    // dispatcher).
    delete wrappedEnv.PLATFORM_SERVICE;

    try {
      return await userWorker.fetch(userRequest, wrappedEnv, ctx);
    } catch (err) {
      if (err instanceof D1EntitlementError) return d1EntitlementResponse();
      throw err;
    }
    });
  }
};
